icons_format = "{icon}"
invert_scrolling = true

[theme]
theme = "ctp-mocha"
[theme.overrides]
separator = ""

[icons]
icons = "none"
[icons.overrides]
music_next = "\uf051"  # fa-forward-step
music_pause = "\uf04c" # fa-pause
music_play = "\uf04b"  # fa-play
music_prev = "\uf048"  # fa-backward-step

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "temperature"
format = " $icon $max "
chip = "@sensors@"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon / $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[[block]]
block = "music"
format = " $icon {$combo.str(max_w:25,rot_interval:0.5) $prev $play $next |}"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S') "

[[block]]
block = "battery"
full_format = " $icon $percentage "
charging_format = " $icon $percentage "
not_charging_format = " $icon $percentage "
empty_format = " $icon $percentage "
